package sk.tuke.seregely.dipl.att.entity;

// Generated Mar 29, 2013 4:53:51 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Dovolenka generated by hbm2java
 */
public class Dovolenka implements java.io.Serializable {

	private int idDovolenky;
	private Zamestnanec zamestnanec;
	private Date koniec;
	private Date zaciatok;
	private Integer stav;

	public Dovolenka() {
	}

	public Dovolenka(int idDovolenky) {
		this.idDovolenky = idDovolenky;
	}

	public Dovolenka(int idDovolenky, Zamestnanec zamestnanec, Date koniec,
			Date zaciatok, Integer stav) {
		this.idDovolenky = idDovolenky;
		this.zamestnanec = zamestnanec;
		this.koniec = koniec;
		this.zaciatok = zaciatok;
		this.stav = stav;
	}

	public int getIdDovolenky() {
		return this.idDovolenky;
	}

	public void setIdDovolenky(int idDovolenky) {
		this.idDovolenky = idDovolenky;
	}

	public Zamestnanec getZamestnanec() {
		return this.zamestnanec;
	}

	public void setZamestnanec(Zamestnanec zamestnanec) {
		this.zamestnanec = zamestnanec;
	}

	public Date getKoniec() {
		return this.koniec;
	}

	public void setKoniec(Date koniec) {
		this.koniec = koniec;
	}

	public Date getZaciatok() {
		return this.zaciatok;
	}

	public void setZaciatok(Date zaciatok) {
		this.zaciatok = zaciatok;
	}

	public Integer getStav() {
		return this.stav;
	}

	public void setStav(Integer stav) {
		this.stav = stav;
	}

}
