package sk.tuke.seregely.dipl.att.entity;

// Generated Mar 29, 2013 4:53:51 PM by Hibernate Tools 4.0.0

/**
 * Personalista generated by hbm2java
 */
public class Personalista implements java.io.Serializable {

	private int idPersonalistu;
	private Oddelenie oddelenie;
	private String celeMeno;

	public Personalista() {
	}

	public Personalista(int idPersonalistu) {
		this.idPersonalistu = idPersonalistu;
	}

	public Personalista(int idPersonalistu, Oddelenie oddelenie, String celeMeno) {
		this.idPersonalistu = idPersonalistu;
		this.oddelenie = oddelenie;
		this.celeMeno = celeMeno;
	}

	public int getIdPersonalistu() {
		return this.idPersonalistu;
	}

	public void setIdPersonalistu(int idPersonalistu) {
		this.idPersonalistu = idPersonalistu;
	}

	public Oddelenie getOddelenie() {
		return this.oddelenie;
	}

	public void setOddelenie(Oddelenie oddelenie) {
		this.oddelenie = oddelenie;
	}

	public String getCeleMeno() {
		return this.celeMeno;
	}

	public void setCeleMeno(String celeMeno) {
		this.celeMeno = celeMeno;
	}

}
