package sk.tuke.seregely.dipl.att.entity;

// Generated Mar 29, 2013 4:53:51 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Praceneschopnost generated by hbm2java
 */
public class Praceneschopnost implements java.io.Serializable {

	private int idPraceneschopnosti;
	private Zamestnanec zamestnanec;
	private Date zaciatok;
	private Date koniec;
	private Integer stav;

	public Praceneschopnost() {
	}

	public Praceneschopnost(int idPraceneschopnosti) {
		this.idPraceneschopnosti = idPraceneschopnosti;
	}

	public Praceneschopnost(int idPraceneschopnosti, Zamestnanec zamestnanec,
			Date zaciatok, Date koniec, Integer stav) {
		this.idPraceneschopnosti = idPraceneschopnosti;
		this.zamestnanec = zamestnanec;
		this.zaciatok = zaciatok;
		this.koniec = koniec;
		this.stav = stav;
	}

	public int getIdPraceneschopnosti() {
		return this.idPraceneschopnosti;
	}

	public void setIdPraceneschopnosti(int idPraceneschopnosti) {
		this.idPraceneschopnosti = idPraceneschopnosti;
	}

	public Zamestnanec getZamestnanec() {
		return this.zamestnanec;
	}

	public void setZamestnanec(Zamestnanec zamestnanec) {
		this.zamestnanec = zamestnanec;
	}

	public Date getZaciatok() {
		return this.zaciatok;
	}

	public void setZaciatok(Date zaciatok) {
		this.zaciatok = zaciatok;
	}

	public Date getKoniec() {
		return this.koniec;
	}

	public void setKoniec(Date koniec) {
		this.koniec = koniec;
	}

	public Integer getStav() {
		return this.stav;
	}

	public void setStav(Integer stav) {
		this.stav = stav;
	}

}
