package sk.tuke.seregely.dipl.att.entity;

// Generated Mar 29, 2013 4:53:51 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PritomnostVPraci generated by hbm2java
 */
public class PritomnostVPraci implements java.io.Serializable {

	private int idPritomnosti;
	private Zamestnanec zamestnanec;
	private Date zaciatok;
	private Date koniec;
	private Integer stav;

	public PritomnostVPraci() {
	}

	public PritomnostVPraci(int idPritomnosti) {
		this.idPritomnosti = idPritomnosti;
	}

	public PritomnostVPraci(int idPritomnosti, Zamestnanec zamestnanec,
			Date zaciatok, Date koniec, Integer stav) {
		this.idPritomnosti = idPritomnosti;
		this.zamestnanec = zamestnanec;
		this.zaciatok = zaciatok;
		this.koniec = koniec;
		this.stav = stav;
	}

	public int getIdPritomnosti() {
		return this.idPritomnosti;
	}

	public void setIdPritomnosti(int idPritomnosti) {
		this.idPritomnosti = idPritomnosti;
	}

	public Zamestnanec getZamestnanec() {
		return this.zamestnanec;
	}

	public void setZamestnanec(Zamestnanec zamestnanec) {
		this.zamestnanec = zamestnanec;
	}

	public Date getZaciatok() {
		return this.zaciatok;
	}

	public void setZaciatok(Date zaciatok) {
		this.zaciatok = zaciatok;
	}

	public Date getKoniec() {
		return this.koniec;
	}

	public void setKoniec(Date koniec) {
		this.koniec = koniec;
	}

	public Integer getStav() {
		return this.stav;
	}

	public void setStav(Integer stav) {
		this.stav = stav;
	}

}
